"""added foreingkey user_name

Revision ID: 649762b05dd7
Revises: ca9a586bad41
Create Date: 2024-01-29 20:03:58.860250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649762b05dd7'
down_revision = 'ca9a586bad41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint('fk_article_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_article_user_id_user'), 'user', ['user_id'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_article_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_article_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
